### ISSUE TITLE
Missing `extern "C"` in etesync.h header

### ISSUE THREAD

**Issue by danvratil** [etesync/etesync-rs#5]
When included from a C++ program, the compiler will try to lookup mangled function names in etesync.so but will fail, since the library is a C library, so the names there are not mangled in there.

The code in the generated header should be wrapped in `extern "C" { ...... }` to indicate to the compiler that the functions there are C functions and that it should lookup unmangled function names in linked libraries.

**Comment by tasn** [comment]
:man_facepalming: nice catch, pushing a fix.
